# Generated by Django 3.2.7 on 2021-09-19 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('short_description', models.CharField(max_length=30)),
                ('long_description', models.CharField(max_length=100)),
                ('github', models.URLField(default='')),
                ('link', models.URLField(default='')),
                ('icon', models.CharField(max_length=20)),
                ('color', models.CharField(max_length=20)),
                ('languages', models.JSONField()),
            ],
        ),
    ]
