# Generated by Django 3.2.7 on 2021-09-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_project_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
                ('technology', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=120)),
                ('project', models.CharField(blank=True, default='', max_length=50)),
                ('link', models.CharField(max_length=150)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='long_description',
            field=models.CharField(max_length=150),
        ),
    ]
