# Generated by Django 3.2.7 on 2021-09-24 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_technology_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='technology',
            new_name='name',
        ),
    ]
