# Generated by Django 3.2.7 on 2021-09-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_technology_technology_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='languages',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
