# Generated by Django 3.2.7 on 2021-10-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20211004_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technology',
            name='description',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
